spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  name: development

numberOfActors: 100000
numberOfSimulators: 10
newActorTimeout: 1

demo:
  locators: localhost[10334]

---
spring:
  config:
    activate:
      on-profile: prod
  name: production

numberOfActors: 1000000
numberOfSimulators: 16

demo:
  locators: localhost[10334]

---
spring:
  config:
    activate:
      on-profile: unit-test
  name: unit test name

demo:
  locators: localhost[10334]
