spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  name: development

demo:
  GeospatialSimulator:
    locators: localhost[10334]
    numberOfActors: 100000
    numberOfSimulators: 10
    newActorTimeout: 1

---
spring:
  config:
    activate:
      on-profile: prod
  name: production



demo:
  GeospatialSimulator:
    locators: localhost[10334]
    numberOfActors: 1000000
    numberOfSimulators: 16

---
spring:
  config:
    activate:
      on-profile: unit-test
  name: unit test name

demo:
  GeospatialSimulator:
    locators: localhost[10334]
